version: '3.8'
services:
  redis-1:
    image: sloopstash/redis:v7.2.1
    entrypoint: /usr/bin/supervisord
    command: "-c /etc/supervisord.conf"
    volumes:
      - redis-data-1:/opt/redis/data
      - redis-log-1:/opt/redis/log
      - ../../supervisor/conf/server.conf:/etc/supervisord.conf
      - ../../redis/${DLK_REDIS_VERSION}/conf/supervisor.ini:/etc/supervisord.d/redis.ini
      - ../../redis/${DLK_REDIS_VERSION}/conf/server.conf:/opt/redis/conf/redis.conf
    networks:
      common:
        ipv4_address: ${DLK_REDIS_1_IP}
  redis-2:
    image: sloopstash/redis:v7.2.1
    entrypoint: /usr/bin/supervisord
    command: "-c /etc/supervisord.conf"
    volumes:
      - redis-data-2:/opt/redis/data
      - redis-log-2:/opt/redis/log
      - ../../supervisor/conf/server.conf:/etc/supervisord.conf
      - ../../redis/${DLK_REDIS_VERSION}/conf/supervisor.ini:/etc/supervisord.d/redis.ini
      - ../../redis/${DLK_REDIS_VERSION}/conf/server.conf:/opt/redis/conf/redis.conf
    networks:
      common:
        ipv4_address: ${DLK_REDIS_2_IP}
  redis-3:
    image: sloopstash/redis:v7.2.1
    entrypoint: /usr/bin/supervisord
    command: "-c /etc/supervisord.conf"
    volumes:
      - redis-data-3:/opt/redis/data
      - redis-log-3:/opt/redis/log
      - ../../supervisor/conf/server.conf:/etc/supervisord.conf
      - ../../redis/${DLK_REDIS_VERSION}/conf/supervisor.ini:/etc/supervisord.d/redis.ini
      - ../../redis/${DLK_REDIS_VERSION}/conf/server.conf:/opt/redis/conf/redis.conf
    networks:
      common:
        ipv4_address: ${DLK_REDIS_3_IP}
  redis-4:
    image: sloopstash/redis:v7.2.1
    entrypoint: /usr/bin/supervisord
    command: "-c /etc/supervisord.conf"
    volumes:
      - redis-data-4:/opt/redis/data
      - redis-log-4:/opt/redis/log
      - ../../supervisor/conf/server.conf:/etc/supervisord.conf
      - ../../redis/${DLK_REDIS_VERSION}/conf/supervisor.ini:/etc/supervisord.d/redis.ini
      - ../../redis/${DLK_REDIS_VERSION}/conf/server.conf:/opt/redis/conf/redis.conf
    networks:
      common:
        ipv4_address: ${DLK_REDIS_4_IP}
  redis-5:
    image: sloopstash/redis:v7.2.1
    entrypoint: /usr/bin/supervisord
    command: "-c /etc/supervisord.conf"
    volumes:
      - redis-data-5:/opt/redis/data
      - redis-log-5:/opt/redis/log
      - ../../supervisor/conf/server.conf:/etc/supervisord.conf
      - ../../redis/${DLK_REDIS_VERSION}/conf/supervisor.ini:/etc/supervisord.d/redis.ini
      - ../../redis/${DLK_REDIS_VERSION}/conf/server.conf:/opt/redis/conf/redis.conf
    networks:
      common:
        ipv4_address: ${DLK_REDIS_5_IP}
  redis-6:
    image: sloopstash/redis:v7.2.1
    entrypoint: /usr/bin/supervisord
    command: "-c /etc/supervisord.conf"
    volumes:
      - redis-data-6:/opt/redis/data
      - redis-log-6:/opt/redis/log
      - ../../supervisor/conf/server.conf:/etc/supervisord.conf
      - ../../redis/${DLK_REDIS_VERSION}/conf/supervisor.ini:/etc/supervisord.d/redis.ini
      - ../../redis/${DLK_REDIS_VERSION}/conf/server.conf:/opt/redis/conf/redis.conf
    networks:
      common:
        ipv4_address: ${DLK_REDIS_6_IP}
volumes:
  redis-data-1:
    driver: local
  redis-data-2:	
    driver: local
  redis-data-3:	
    driver: local	
  redis-data-4:	
    driver: local
  redis-data-5:	
    driver: local
  redis-data-6:	
    driver: local
  redis-log-1:	
    driver: local
  redis-log-2:	
    driver: local
  redis-log-3:	
    driver: local
  redis-log-4:	
    driver: local
  redis-log-5:	
    driver: local
  redis-log-6:	
    driver: local		
networks:
  common:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${DLK_REDIS_NETWORK}
